export { default as Button } from './Button'
export { default as SearchItem } from './SearchItem'
export { default as PageNumber } from './PageNumber'
export { default as Contact } from './Contact'
export { default as Modal } from './Modal'
export { default as ItemSidebar } from './ItemSidebar'
export { default as Item } from './Item'
export { default as DistrictBtn } from './DistrictBtn' 
// export { default as ProvinceBtn } from './ProvinceBtn'
// export { default as Province } from './Province'
export { default as Intro } from './Intro'
export { default as Header } from './Header'
export { default as NewPostItem} from './NewPostItem'
export {default as DemoModal} from './DemoModal'
export {default as PostItem} from './PostItem'